[package]
name = "weboff"
version = "0.1.0"
edition = "2021"

[dependencies]
tao = "0.32.8"
wry = "0.50.5"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"

[build]
rustflags = ["-C", "target-cpu=native"]